manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: samvtran
      url-base: https://github.com/samvtran
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: Rechtek-zmk-config
      remote: samvtran
      revision: main
  self:
    path: config
